const COMMUNITY_TYPES = [
    { type: 'General' },
    { type: 'Sports' },
    { type: 'Religion' },
    { type: 'Food' },
    { type: 'Music and Dance' },
    { type: 'Language and Literature' },
    { type: 'History and Heritage' },
    { type: 'Festivals and Celebrations' },
    { type: 'Fashion and Clothing' },
    { type: 'Art and Craft' },
    { type: 'Travel and Tourism' },
    { type: 'Customs and Traditions' },
    { type: 'Cinema and Theater' },
    { type: 'Health and Wellness' },
    { type: 'Technology and Innovation' },
    { type: 'Education and Learning' },
    { type: 'Nature and Environment' },
    { type: 'Social Issues' },
    { type: 'Family and Relationships' },
    { type: 'Spirituality and Philosophy' },
    { type: 'Gaming' },
    { type: 'Mythology and Folklore' },
    { type: 'Pets and Animals' },
    { type: 'Hobbies and Crafts' },
    { type: 'Adventure and Outdoor Activities' },
    { type: 'Urban and Rural Life' },
    { type: 'Holidays and Traditions' },
    { type: 'Media and Journalism' }
];
export { COMMUNITY_TYPES }
